### ISSUE TITLE
Exception with pyramid_handlers, url dispatch

### ISSUE THREAD

**Issue by msander** [FormAlchemy/fa.jquery#1]
An exception occures when trying to use fa.jquery with pyramid_handlers and url dispatch (haven't tried other setups..)

Somehow jqgrid.pt doesn't get the context and context.view variables.

Update:

Tried to change listing.pt to:

```
<div tal:content="structure fs.render(renderer='fa.jquery:templates/forms/jqgrid.pt', request=request, context=context, view=view)" />
```

This does not resolve the issue because 'collection' isn't set. Don't know what exactly it does.

<pre>
URL: http://dev.myproject.de/admin/Publisher
File '/usr/local/lib/python2.6/dist-packages/WebError-0.10.2-py2.6.egg/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/usr/local/lib/python2.6/dist-packages/repoze.tm2-1.0b1-py2.6.egg/repoze/tm/__init__.py', line 23 in __call__
  result = self.application(environ, save_status_and_headers)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/router.py', line 158 in __call__
  response = view_callable(context, request)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/config.py', line 2617 in __call__
  return view(context, request)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/config.py', line 2805 in attr_view
  return view(context, request)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/config.py', line 2784 in predicate_wrapper
  return view(context, request)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/config.py', line 2839 in _rendered_view
  context)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/renderers.py', line 294 in render_view
  request=request)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/renderers.py', line 322 in render_to_response
  result = self.render(value, system_values, request=request)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/renderers.py', line 318 in render
  result = renderer(value, system_values)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/chameleon_zpt.py', line 52 in __call__
  result = self.template(**system)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 104 in __call__
  return self.render(**kwargs)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 402 in render
  return super(TemplateFile, self).render(*args, **kwargs)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/zpt/template.py', line 17 in render
  return super(PageTemplate, self).render(*args, **kwargs)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 229 in render
  return self.cook_and_render(kwargs, utils.emptydict, None, True)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 382 in cook_and_render
  args, slots, macro, global_scope)
(<PageTemplateFile /usr/local/lib/python2.6/dist-packages/fa.jquery-0.8-py2.6.egg/fa/jquery/templates/admin/listing.pt>,)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 217 in cook_and_render
  utils.raise_template_exception(kwargs, sys.exc_info())
File '/tmp/tmpmyUSaG/listing.pt.py', line 173 in render
  _metal.render(_tmp, _out=_out, _write=_write, _domain=_domain, econtext=econtext)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 428 in render
  return self.render(name, slots=slots, parameters=kwargs)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/zpt/template.py', line 22 in render_macro
  macro, global_scope=global_scope, slots=slots, parameters=parameters)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 239 in render_macro
  return self.cook_and_render(parameters, slots, macro, global_scope)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 382 in cook_and_render
  args, slots, macro, global_scope)
(<PageTemplateFile /usr/local/lib/python2.6/dist-packages/fa.jquery-0.8-py2.6.egg/fa/jquery/templates/admin/master.pt>,)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 217 in cook_and_render
  utils.raise_template_exception(kwargs, sys.exc_info())
File '/tmp/tmpmyUSaG/listing.pt.py', line 69 in _callback_main
  _content = _lookup_attr(econtext['fs'], 'render')(renderer='fa.jquery:templates/forms/jqgrid.pt', request=econtext['request'])
File '/usr/local/lib/python2.6/dist-packages/FormAlchemy-1.3.6-py2.6.egg/formalchemy/tables.py', line 102 in render
  return engine('grid_readonly', collection=self, **kwargs)
File '/usr/local/lib/python2.6/dist-packages/FormAlchemy-1.3.6-py2.6.egg/formalchemy/templates.py', line 66 in __call__
  return self.render(template_name, **kw)
File '/usr/local/lib/python2.6/dist-packages/pyramid_formalchemy-0.1-py2.6.egg/pyramid_formalchemy/utils.py', line 24 in render
  return literal(render(renderer, kwargs))
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/renderers.py', line 68 in render
  return helper.render(value, None, request=request)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/renderers.py', line 318 in render
  result = renderer(value, system_values)
File '/usr/local/lib/python2.6/dist-packages/pyramid-1.0-py2.6.egg/pyramid/chameleon_zpt.py', line 52 in __call__
  result = self.template(**system)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 104 in __call__
  return self.render(**kwargs)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 402 in render
  return super(TemplateFile, self).render(*args, **kwargs)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/zpt/template.py', line 17 in render
  return super(PageTemplate, self).render(*args, **kwargs)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 229 in render
  return self.cook_and_render(kwargs, utils.emptydict, None, True)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 382 in cook_and_render
  args, slots, macro, global_scope)
(<PageTemplateFile /usr/local/lib/python2.6/dist-packages/fa.jquery-0.8-py2.6.egg/fa/jquery/templates/forms/jqgrid.pt>,)
File '/usr/local/lib/python2.6/dist-packages/Chameleon-1.3.0_rc1-py2.6.egg/chameleon/core/template.py', line 217 in cook_and_render
  utils.raise_template_exception(kwargs, sys.exc_info())
File '/tmp/tmpJUgO5k/jqgrid.pt.py', line 34 in render
  colmodels = _lookup_attr(',', 'join')([_lookup_attr(_lookup_attr(f, 'metadata'), 'get')('json') for f in _lookup_attr(_lookup_attr(econtext['collection'], 'render_fields'), 'values')()])
RuntimeError: Caught exception rendering template.
 - Expression: ``main.macros['master']``
 - Filename:   /usr/local/lib/python2.6/dist-packages/fa.jquery-0.8-py2.6.egg/fa/jquery/templates/admin/listing.pt
 - Arguments:  fs: <Grid - at 0xae3a48c>
               renderer_name: pyramid_formalchemy:templates/admin/listing.pt
               context: <ModelListing Publisher at 0xae2f4ac>
               xincludes: <XIncludes - at 0xae33d0c>
               request: <RequestWithUserAttribute - at 0xae2f3ec>
               tmpl_context: <TemplateContext - at 0xae33c4c>
               F_: <instancemethod gettext at 0xae3102c>
               renderer_info: <RendererHelper - at 0xadf5bcc>
               session: <PyramidBeakerSessionObject - at 0xae33bec>
               pager: 
               id: <NoneType - at 0x8231098>
               c: <TemplateContext - at 0xae33c4c>
               breadcrumb: <list - at 0xae3a3ac>
               url: <function route_url at 0xa0c3e9c>
               h: <module myproject.lib.helpers at 0xa916bfc>
               is_grid: True
               macros: <Macros - at 0xae3d4ec>
               template: <PageTemplateFile - at 0xae33e4c>
               main: <PageTemplateFile - at 0xae3a32c>
               model_name: Publisher
               view: <ModelView - at 0xae2f4cc>

RuntimeError: Caught exception rendering template.
 - Expression: ``fs.render(renderer='fa.jquery:templates/forms/jqgrid.pt', request=request)``
 - Filename:   /usr/local/lib/python2.6/dist-packages/fa.jquery-0.8-py2.6.egg/fa/jquery/templates/admin/master.pt
 - Arguments:  macros: <Macros - at 0xae3a8ec>

RuntimeError: Caught exception rendering template.
 - Expression: ``','.join([f.metadata.get('json') for f in collection.render_fields.values()])``
 - Filename:   /usr/local/lib/python2.6/dist-packages/fa.jquery-0.8-py2.6.egg/fa/jquery/templates/forms/jqgrid.pt
 - Arguments:  renderer_name: fa.jquery:templates/forms/jqgrid.pt
               template: <PageTemplateFile - at 0xae5f1cc>
               xincludes: <XIncludes - at 0xae63acc>
               tmpl_context: <TemplateContext - at 0xae33c4c>
               collection: <Grid - at 0xae3a48c>
               F_: <instancemethod gettext at 0xae3c25c>
               renderer_info: <RendererHelper - at 0x9a6a3cc>
               session: <Electroencephalographic - at 0xae33bec>
               c: <TemplateContext - at 0xae33c4c>
               fatypes: <module formalchemy.fatypes at 0xaa49d1c>
               url: <function route_url at 0xa0c3e9c>
               h: <module myproject.lib.helpers at 0xa916bfc>
               request: <RequestWithUserAttribute - at 0xae2f3ec>
               macros: <Macros - at 0xae60a0c>
               html: <module formalchemy.helpers at 0xaa4950c>
               context: <NoneType - at 0x8231098>
               view: <NoneType - at 0x8231098>

TypeError: sequence item 0: expected string, NoneType found
</pre>

**Comment by gawel** [comment]
As I remember I've saw this bug a few days ago and it's already fixed. Need to be checked though..
